// Generated by gencpp from file project2fetch/gripperStatus.msg
// DO NOT EDIT!


#ifndef PROJECT2FETCH_MESSAGE_GRIPPERSTATUS_H
#define PROJECT2FETCH_MESSAGE_GRIPPERSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace project2fetch
{
template <class ContainerAllocator>
struct gripperStatus_
{
  typedef gripperStatus_<ContainerAllocator> Type;

  gripperStatus_()
    : gripper_closed(false)  {
    }
  gripperStatus_(const ContainerAllocator& _alloc)
    : gripper_closed(false)  {
  (void)_alloc;
    }



   typedef uint8_t _gripper_closed_type;
  _gripper_closed_type gripper_closed;





  typedef boost::shared_ptr< ::project2fetch::gripperStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::project2fetch::gripperStatus_<ContainerAllocator> const> ConstPtr;

}; // struct gripperStatus_

typedef ::project2fetch::gripperStatus_<std::allocator<void> > gripperStatus;

typedef boost::shared_ptr< ::project2fetch::gripperStatus > gripperStatusPtr;
typedef boost::shared_ptr< ::project2fetch::gripperStatus const> gripperStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::project2fetch::gripperStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::project2fetch::gripperStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::project2fetch::gripperStatus_<ContainerAllocator1> & lhs, const ::project2fetch::gripperStatus_<ContainerAllocator2> & rhs)
{
  return lhs.gripper_closed == rhs.gripper_closed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::project2fetch::gripperStatus_<ContainerAllocator1> & lhs, const ::project2fetch::gripperStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace project2fetch

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::project2fetch::gripperStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::project2fetch::gripperStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project2fetch::gripperStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project2fetch::gripperStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project2fetch::gripperStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project2fetch::gripperStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::project2fetch::gripperStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0bb9f49e5ee44b74c38bc58a62045bee";
  }

  static const char* value(const ::project2fetch::gripperStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0bb9f49e5ee44b74ULL;
  static const uint64_t static_value2 = 0xc38bc58a62045beeULL;
};

template<class ContainerAllocator>
struct DataType< ::project2fetch::gripperStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "project2fetch/gripperStatus";
  }

  static const char* value(const ::project2fetch::gripperStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::project2fetch::gripperStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool gripper_closed\n"
"\n"
;
  }

  static const char* value(const ::project2fetch::gripperStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::project2fetch::gripperStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gripper_closed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gripperStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::project2fetch::gripperStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::project2fetch::gripperStatus_<ContainerAllocator>& v)
  {
    s << indent << "gripper_closed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gripper_closed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROJECT2FETCH_MESSAGE_GRIPPERSTATUS_H
